name: unified_distributor
description: A powerful and efficient tool for packaging and publishing your applications with ease.
version: 0.2.6
homepage: https://fastforge.dev
repository: https://github.com/fastforgedev/fastforge/tree/main/packages/unified_distributor
issue_tracker: https://github.com/fastforgedev/fastforge/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  ansicolor: 2.0.1
  args: 2.3.1
  charset: 2.0.1
  dio: 5.3.4
  flutter_app_builder:
    git:
      url: https://github.com/dsc7219356/flutter_distributor.git
      path: packages/flutter_app_builder
  flutter_app_packager:
    git:
      url: https://github.com/dsc7219356/flutter_distributor.git
      path: packages/flutter_app_packager
  flutter_app_publisher:
    git:
      url: https://github.com/dsc7219356/flutter_distributor.git
      path: packages/flutter_app_publisher
  logging: 1.0.2
  path: 1.8.3
  pubspec_parse: 1.2.3
  shell_executor:
    git:
      url: https://github.com/dsc7219356/flutter_distributor.git
      path: packages/shell_executor
  shell_uikit:
    git:
      url: https://github.com/dsc7219356/flutter_distributor.git
      path: packages/shell_uikit
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.23.1
